CONFIG_COMPILER_WARNINGS_AS_ERRORS=y

# CONFIG_SCHED_THREAD_USAGE_ALL=n makes sched_cpu_update_usage() a no-op macro
CONFIG_THREAD_RUNTIME_STATS=y
CONFIG_SCHED_THREAD_USAGE=y
CONFIG_SCHED_THREAD_USAGE_ANALYSIS=y
CONFIG_SCHED_THREAD_USAGE_ALL=n

# pull z_thread_stats_reset() into the build
CONFIG_OBJ_CORE=y
CONFIG_OBJ_CORE_THREAD=y
CONFIG_OBJ_CORE_STATS=y
CONFIG_OBJ_CORE_STATS_SYSTEM=n
CONFIG_OBJ_CORE_STATS_THREAD=y
